### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by samyak-jain** [lucastan/uva-node#19]
![screen shot 2017-06-04 at 11 56 55 am](https://cloud.githubusercontent.com/assets/10133258/26759508/f9fea982-491c-11e7-840e-3fb142d61ee2.png)

i followed the exact instructions as on README. I am running OSX. 

The adapData is empty for some reason so it coming as undefined while running

![screen shot 2017-06-04 at 11 58 47 am](https://cloud.githubusercontent.com/assets/10133258/26759564/7724aca8-491e-11e7-9122-7cbbaae05053.png)

**Comment by lucastan** [comment]
fixed, can you retry?

can you check whether you can download the problem list at http://uhunt.felix-halim.net/api/p
