### ISSUE TITLE
send failed: cannot login.

### ISSUE THREAD

**Issue by roadbike80** [lucastan/uva-node#27]
Hi, I am running the latest version

```
uva-node@0.1.13
```
I have updated my password to be sure
However send always fails.

```
uva send 10012 sol.cpp
Logging in...
Sending code...
send failed: cannot login. password correct?
```

Is there an issue related to changes at the online judge?

**Comment by guestname** [comment]
I'm having the same problem.

**Comment by Parimal7** [comment]
Same issue, please look into it.

**Comment by EvenPeng** [comment]
Hi all, I created a PR #29  to fix it.

**Comment by lucastan** [comment]
new version 0.1.14

**Comment by roadbike80** [comment]
Fix verified. Thank you!
